language: android

sudo: required
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
jdk: oraclejdk8
os:
 - linux

script:
 - ./gradlew build
